name: Run Tests Manually

on:
  workflow_dispatch:
    inputs:
      testname:
        description: 'Name of the test to run'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
      - name: Test with pytest
        run: |
          pytest ${{ github.event.inputs.testname }}
