name: Run Python Tests

on:
  workflow_dispatch:
    inputs:
      pytest_test_names:
        description: 'Pytest test names (e.g., test_new_company or test_visit_license_website)'
        required: false

jobs:
  run-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Create virtual environment
      run: |
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1

    - name: Install dependencies
      run: |
        .\.venv\Scripts\Activate.ps1
        pip install -r requirements.txt
        pip install pytest-html
        playwright install --with-deps

    - name: Run Tests
      run: |
        .\.venv\Scripts\Activate.ps1
        if [ -z "${{ github.event.inputs.pytest_test_names }}" ]; then
          pytest -v --html=pytest_report.html --self-contained-html
        else
          pytest -v -k "${{ github.event.inputs.pytest_test_names }}" --html=pytest_report.html --self-contained-html
        fi

    - name: Display test results summary
      if: always()
      run: |
        echo "Test Results Summary:"
        cat pytest_report.html | grep -A 5 "<h2>Summary</h2>"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: |
          pytest_report.html