name: Schedule Python Tests on Windows

on:
  workflow_dispatch:
#  schedule:
#    - cron: '02 16 * * *'

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Playwright browsers
      run: python -m playwright install

    - name: Run tests
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      run: |
        pytest

    - name: Commit and push if List.txt has changed
      env:
        PUSH_GITHUB_TOKEN: ${{ secrets.PUSH_GITHUB_TOKEN }}
      run: |
        git config --local user.email "osmangungor83@gmail.com"
        git config --local user.name "Osman Güngör"
        git add List.txt
        git commit -m "Update List.txt with test results" || exit 0
        git push origin HEAD:master


    - name: Commit and push if List_api.txt has changed
      env:
        PUSH_GITHUB_TOKEN: ${{ secrets.PUSH_GITHUB_TOKEN }}
      run: |
        git config --local user.email "osmangungor83@gmail.com"
        git config --local user.name "Osman Güngör"
        git add list_api.txt 
        git commit -m "Update list_api.txt with test results" || exit 0
        git push origin HEAD:master
