name: Schedule API Tests and Send Email on Windows

on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  run-tests-and-send-email:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API test and save results
      run: pytest tests/api_test.py > test_results.txt
    - name: Send email
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        python -c "
        import os
        import sendgrid
        from sendgrid.helpers.mail import Mail, Email, To, Content

        sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
        from_email = Email('your-email@example.com')  # Replace with your from email address
        to_email = To('your-email@example.com')       # Replace with your to email address
        subject = 'API Test Results'
        with open('test_results.txt', 'r') as file:
            data = file.read()
        content = Content('text/plain', data)
        mail = Mail(from_email, to_email, subject, content)
        response = sg.client.mail.send.post(request_body=mail.get())
        "
