name: Schedule Python Tests on Windows

on:

  workflow_dispatch:
#  schedule:
#    - cron: '02 16 * * *'

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Display requirements.txt
      run: cat requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}  # Use the secret name you configured in GitHub Secrets
      run: |
        pytest
